### ISSUE TITLE
[0h] Fix "updated_at" value in "transactions" API response

### ISSUE THREAD

**Issue by shdwdmn** [UOSnetwork/ucom.backend#111]
"updated_at" time value is different from "raw_tr_data" block by 4 hours back in "transactions" API response . As a result, Transfers times in Wallet are displayed wrong (4 hours back).

![image](https://user-images.githubusercontent.com/46528935/56419113-d982de80-62a1-11e9-97fc-981009a0457c.png)

**Comment by vladimirice** [comment]
not required to solve due to a new mini-mongo integration
