### ISSUE TITLE
Unable to create new U.OS account due to "account name is taken" error for every account name

### ISSUE THREAD

**Issue by shdwdmn** [UOSnetwork/ucom.backend#129]
Server responds with 400 error on every valid validate-account-name request.
![image](https://user-images.githubusercontent.com/46528935/57683281-07a6d480-763c-11e9-9e1f-5511f66131e1.png)

**Comment by vladimirice** [comment]
resolved. Blockchain node was down due to the reboot and a lack of durability (ACID)
