### ISSUE TITLE
[0h] Unable to delete the last Administrator (not the owner) from the Community

### ISSUE THREAD

**Issue by shdwdmn** [UOSnetwork/ucom.backend#153]
The last Administrator cannot be deleted from the Community: blank users_team[] is passed to /api/v1/organizations/NNN, but the last user is not deleted from Administrators after all.
![image](https://user-images.githubusercontent.com/46528935/58489277-9acf2680-8173-11e9-95db-229daa086de1.png)

### Steps to reproduce:
1. Find or create a Community with at least one Administrator added (or team member or on board member) except the Community Owner
2. Delete the last Administrator from the Edit Community page
![image](https://user-images.githubusercontent.com/46528935/58489453-fb5e6380-8173-11e9-87e9-acfa486552ae.png)
3. Check if the deleted User is still the Community Administrator

### Expected result:
User is deleted, the Community Owner is the last Administrator.

### Actual result:
User is not deleted, the Community still has 2 Administrators.
![image](https://user-images.githubusercontent.com/46528935/58489700-74f65180-8174-11e9-9d0a-f8a5edfa31f6.png)

**Comment by vladimirice** [comment]
resolved in #172
