### ISSUE TITLE
[3h] Content upvote details - architecture

### ISSUE THREAD

**Issue by Sxela** [UOSnetwork/ucom.backend#201]
Content upvote details

Hover with total number of upvoters, downvoters.

Popup with a list of users, filters for:
upvoters, downvoters, total

Pagination, following status display.

https://www.figma.com/file/UDeXhKfd7BiuWrGfLzoUlpwS/U%C2%B0Community-v.1.2?node-id=6072%3A480

**Comment by Sxela** [comment]
![Frame2](https://user-images.githubusercontent.com/11751592/61861609-fa785280-aed4-11e9-85a3-8f2939f8f3a6.png)

**Comment by vladimirice** [comment]
* Communications and questions, suggestions about how to decrease cost without decreasing a profit
* Tasks decomposition, how-to-resolve plan (listed in the every new related task)
